services:
  golang-api:
    build:
      context: ./golang-api
      dockerfile: Dockerfile
    container_name: techpulse-golang-api
    env_file:
      - ./.env
    environment:
      PYTHON_AI_BASE_URL: http://python-api:8001
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - python-api

  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    container_name: techpulse-python-ai
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    restart: unless-stopped
